---
# extraLabels:
#   - "traefik.http.routers.grafana.rule=grafana.localhost"
#   - "traefik.http.routers.grafana.service=grafana"
#   - "traefik.http.routers.grafana.middlewares=traefik-auth"
#   - "traefik.http.services.grafana.loadbalancer.server.port=3000"
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-prometheus-server
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        jsonData:
          timeout: 60
          maxLines: 1000
