---
# server:
#   podLabels:
#     - "traefik.http.routers.prometheus.rule=prometheus.localhost"
#     - "traefik.http.routers.prometheus.service=prometheus"
#     - "traefik.http.routers.prometheus.middlewares=traefik-auth"
#     - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: traefik
    metrics_path: /metrics
    static_configs:
      - targets: ['traefik:9100']
