---
name: 'Golang'

'on':
  push:
    paths:
      - '**/*.go'
      - '**/*_test.go'
    branches:
      - 'main'
  pull_request:
    paths:
      - '**/*.go'
      - '**/*_test.go'

jobs:
  golang:
    name: "Golang checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Verify dependencies
        run: go mod verify

      # - name: Build
      #   run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...

      - name: Run tests
        run: go test -race -vet=off ./...
