name: 'Terraform'

on:
  push:
    paths:
    - infrastructure/**

  pull_request:

jobs:
  terraform:
    name: 'Terraform Format'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Format
      run: terraform fmt -check
